// ═══════════════════════════════════════════════════════════════════════════════
// AHK# Bridge — Declarations: writes an editor declaration file for the AHK language server (CS.Declare)
// (part of ahk#.bridge.dll)
// ═══════════════════════════════════════════════════════════════════════════════
// The output is a `.d.ahk`: classes without bodies that describe CS.System.Text.StringBuilder & co. The
// language server loads `ahk#.d.ahk` automatically next to `ahk#.ahk`, so completion, hover and signature help
// work for the types listed in it. It is never executed.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;

internal static class Declarations
{
    private static readonly Regex _ident = new Regex("^[A-Za-z_][A-Za-z0-9_]*$");
    private static readonly HashSet<string> _skip = new HashSet<string>(StringComparer.Ordinal)
        { "Equals", "GetHashCode", "GetType", "ReferenceEquals", "MemberwiseClone", "Finalize", "Prototype", "Base", "__New", "__Init", "__Delete", "__Item", "Call" };

    private class Node
    {
        public SortedDictionary<string, Node> Children = new SortedDictionary<string, Node>(StringComparer.Ordinal);
        public List<Type> Types = new List<Type>();
    }

    private static bool Usable(Type t)
    {
        return t.IsPublic && !t.IsGenericTypeDefinition && !t.IsNested && _ident.IsMatch(t.Name) && t.Namespace != null;
    }

    // Everything a spec names: a type, or every usable public type of a namespace
    public static List<Type> Expand(IEnumerable<string> specs)
    {
        List<Type> result = new List<Type>();
        foreach (string spec in specs)
        {
            string s = (spec ?? "").Trim();
            if (s.Length == 0) continue;
            Type t = TypeResolver.Resolve(s);
            if (t != null)
            {
                if (Usable(t) && !result.Contains(t)) result.Add(t);
                continue;
            }
            TypeResolver.EnsureCommonAssemblies(s);
            foreach (Assembly asm in TypeResolver.AllAssemblies())
            {
                Type[] exported;
                try { exported = asm.GetExportedTypes(); } catch { continue; }
                foreach (Type e in exported)
                    if (e.Namespace == s && Usable(e) && !result.Contains(e)) result.Add(e);
            }
        }
        return result;
    }

    public static string Generate(IEnumerable<string> specs)
    {
        List<Type> types = Expand(specs);
        HashSet<Type> known = new HashSet<Type>(types);

        Node root = new Node();
        foreach (Type t in types)
        {
            Node n = root;
            foreach (string seg in t.Namespace.Split('.'))
            {
                Node child;
                if (!n.Children.TryGetValue(seg, out child)) { child = new Node(); n.Children[seg] = child; }
                n = child;
            }
            n.Types.Add(t);
        }

        StringBuilder sb = new StringBuilder();
        sb.Append("; AHK# editor declarations: generated by CS.Declare(). Never executed; the AHK language server reads it\n");
        sb.Append("; because it sits next to ahk#.ahk. Add types or namespaces with CS.Declare(\"System.IO\", \"System.Text.StringBuilder\").\n");
        sb.Append("class CS {\n");
        sb.Append("    /** Members every .NET object proxy has (they only apply when the .NET type has no member of the same name). */\n");
        sb.Append("    class _Object {\n");
        sb.Append("        ToAHK() => \"\"\n        ToBuffer() => \"\"\n        FromBuffer(buffer, bytes := \"\") => this\n");
        sb.Append("        Await(timeoutMs := 0) => \"\"\n        Then(onOk := \"\", onFail := \"\") => CSPromise()\n        Catch(onFail) => CSPromise()\n");
        sb.Append("        Finally(fn) => CSPromise()\n        Timeout(ms, cancelSource := \"\") => CSPromise()\n        ToPromise() => CSPromise()\n");
        sb.Append("        On(eventName, handler) => this\n        Off(eventName := \"\") => this\n        Is(typeName) => 0\n");
        sb.Append("        Dispose() => \"\"\n        AutoDispose() => this\n        Type() => \"\"\n        Raw() => \"\"\n        Members() => \"\"\n        _Invoke(name, args*) => \"\"\n        _Explain(name, args*) => \"\"\n");
        sb.Append("    }\n");
        Emit(sb, root, 1, known);
        sb.Append("}\n");
        return sb.ToString();
    }

    private static void Emit(StringBuilder sb, Node node, int depth, HashSet<Type> known)
    {
        string pad = new string(' ', depth * 4);
        HashSet<string> taken = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (Type t in node.Types.OrderBy(x => x.Name, StringComparer.Ordinal))
        {
            if (!taken.Add(t.Name) || node.Children.ContainsKey(t.Name)) continue;
            EmitType(sb, t, pad, known);
        }
        foreach (KeyValuePair<string, Node> kv in node.Children)
        {
            if (!_ident.IsMatch(kv.Key) || taken.Contains(kv.Key)) continue;
            sb.Append(pad).Append("class ").Append(kv.Key).Append(" {\n");
            Emit(sb, kv.Value, depth + 1, known);
            sb.Append(pad).Append("}\n");
        }
    }

    // .NET type → AHK type word for JSDoc, or CS.Full.Name when it is one of the declared types
    private static string AhkType(Type t, HashSet<Type> known)
    {
        if (t.IsByRef) t = t.GetElementType();
        if (t == typeof(void)) return "";
        if (known.Contains(t)) return "CS." + t.FullName;
        if (t == typeof(string) || t == typeof(char)) return "String";
        if (t == typeof(bool) || t == typeof(byte) || t == typeof(sbyte) || t == typeof(short) || t == typeof(ushort)
            || t == typeof(int) || t == typeof(uint) || t == typeof(long) || t == typeof(ulong) || t.IsEnum) return "Integer";
        if (t == typeof(float) || t == typeof(double) || t == typeof(decimal)) return "Float";
        if (t.IsArray) return "Array";
        return "Any";
    }

    private static string ParamList(ParameterInfo[] ps, int minCount)
    {
        List<string> parts = new List<string>();
        for (int i = 0; i < ps.Length; i++)
        {
            string name = _ident.IsMatch(ps[i].Name ?? "") ? ps[i].Name : "arg" + (i + 1);
            if (name == "this" || name == "in" || name == "is" || name == "as" || name == "if" || name == "or" || name == "and" || name == "not"
                || name == "for" || name == "try" || name == "class" || name == "throw" || name == "return" || name == "while" || name == "loop"
                || name == "catch" || name == "else" || name == "static" || name == "switch" || name == "until" || name == "case" || name == "get" || name == "set")
                name = name + "_";
            parts.Add(i >= minCount ? name + " := \"\"" : name);
        }
        return string.Join(", ", parts.ToArray());
    }

    private static void EmitMethodGroup(StringBuilder sb, string pad, string name, List<MethodBase> group, bool isStatic, string retDoc, bool ctor)
    {
        // one declaration per name: the longest overload, parameters beyond the shortest overload optional
        MethodBase longest = group.OrderByDescending(m => m.GetParameters().Length).First();
        int min = group.Min(m => m.GetParameters().Length);
        ParameterInfo[] ps = longest.GetParameters();
        sb.Append(pad).Append("/**\n");
        foreach (MethodBase m in group.OrderBy(x => x.GetParameters().Length).Take(8))
            sb.Append(pad).Append(" * ").Append(name).Append("(").Append(string.Join(", ", m.GetParameters().Select(p => Discovery.TypeName(p.ParameterType) + " " + p.Name).ToArray())).Append(")\n");
        if (group.Count > 8) sb.Append(pad).Append(" * ... ").Append(group.Count - 8).Append(" more overloads\n");
        if (retDoc.Length > 0) sb.Append(pad).Append(" * @returns {").Append(retDoc).Append("}\n");
        sb.Append(pad).Append(" */\n");
        sb.Append(pad).Append(isStatic ? "static " : "").Append(name).Append("(").Append(ParamList(ps, min)).Append(") => ")
            .Append("\"\"\n");
    }

    private static void EmitType(StringBuilder sb, Type t, string pad, HashSet<Type> known)
    {
        string kind = t.IsEnum ? "enum" : t.IsInterface ? "interface" : t.IsValueType ? "struct" : (t.IsAbstract && t.IsSealed) ? "static class" : "class";
        sb.Append(pad).Append("/** ").Append(t.FullName).Append(" (").Append(kind).Append(") */\n");
        sb.Append(pad).Append("class ").Append(t.Name).Append(" extends CS._Object {\n");
        string ip = pad + "    ";

        if (t.IsEnum)
        {
            foreach (string n in Enum.GetNames(t))
                if (_ident.IsMatch(n)) sb.Append(ip).Append("static ").Append(n).Append(" => \"\"\n");
            sb.Append(pad).Append("}\n");
            return;
        }

        // constructors
        ConstructorInfo[] ctors = t.IsAbstract ? new ConstructorInfo[0] : t.GetConstructors(BindingFlags.Public | BindingFlags.Instance);
        if (ctors.Length > 0)
            EmitMethodGroup(sb, ip, "__New", ctors.Cast<MethodBase>().ToList(), false, "", true);

        // methods (a static class has no use for the members it inherits from object)
        bool staticClass = t.IsAbstract && t.IsSealed;
        foreach (IGrouping<string, MethodInfo> g in t.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.FlattenHierarchy)
            .Where(m => !m.IsSpecialName && !_skip.Contains(m.Name) && _ident.IsMatch(m.Name) && !m.IsGenericMethodDefinition
                && !(staticClass && m.DeclaringType == typeof(object)))
            .GroupBy(m => (m.IsStatic ? "s:" : "i:") + m.Name).OrderBy(x => x.Key, StringComparer.Ordinal))
        {
            List<MethodBase> group = g.Cast<MethodBase>().ToList();
            bool isStatic = g.First().IsStatic;
            string ret = "";
            Type rt = g.First().ReturnType;
            if (g.All(m => m.ReturnType == rt))
                ret = (rt == t && !isStatic) ? "CS." + t.FullName : AhkType(rt, known);
            EmitMethodGroup(sb, ip, g.First().Name, group, isStatic, ret, false);
        }

        // properties and fields (a property may not share its name with a method of the same side in an AHK class)
        HashSet<string> seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (MethodInfo m in t.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.FlattenHierarchy))
            if (!m.IsSpecialName && !m.IsGenericMethodDefinition && !_skip.Contains(m.Name)) { seen.Add("s:" + m.Name); seen.Add("i:" + m.Name); }
        foreach (PropertyInfo p in t.GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.FlattenHierarchy))
        {
            if (p.GetIndexParameters().Length > 0 || !_ident.IsMatch(p.Name) || _skip.Contains(p.Name)) continue;
            MethodInfo g = p.GetGetMethod(), s = p.GetSetMethod();
            if (g == null && s == null) continue;
            bool isStatic = (g ?? s).IsStatic;
            if (!seen.Add((isStatic ? "s:" : "i:") + p.Name)) continue;
            string ty = AhkType(p.PropertyType, known);
            sb.Append(ip).Append("/** ").Append(Discovery.TypeName(p.PropertyType)).Append(ty.Length > 0 ? "\n" + ip + " * @type {" + ty + "}" : "").Append(" */\n");
            if (s != null && g != null)
                sb.Append(ip).Append(isStatic ? "static " : "").Append(p.Name).Append(" {\n").Append(ip).Append("    get => \"\"\n").Append(ip).Append("    set => \"\"\n").Append(ip).Append("}\n");
            else
                sb.Append(ip).Append(isStatic ? "static " : "").Append(p.Name).Append(" => \"\"\n");
        }
        foreach (FieldInfo f in t.GetFields(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.FlattenHierarchy))
        {
            if (!_ident.IsMatch(f.Name) || _skip.Contains(f.Name) || !seen.Add((f.IsStatic ? "s:" : "i:") + f.Name)) continue;
            string ty = AhkType(f.FieldType, known);
            sb.Append(ip).Append("/** ").Append(Discovery.TypeName(f.FieldType)).Append(ty.Length > 0 ? "\n" + ip + " * @type {" + ty + "}" : "").Append(" */\n");
            if (f.IsInitOnly || f.IsLiteral)
                sb.Append(ip).Append(f.IsStatic ? "static " : "").Append(f.Name).Append(" => \"\"\n");
            else
                sb.Append(ip).Append(f.IsStatic ? "static " : "").Append(f.Name).Append(" {\n").Append(ip).Append("    get => \"\"\n").Append(ip).Append("    set => \"\"\n").Append(ip).Append("}\n");
        }
        sb.Append(pad).Append("}\n");
    }
}
